# Generated by Django 3.1.14 on 2022-01-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name_forward',
            field=models.CharField(blank=True, help_text='Inverse relation like: "is sub-class of" vs. "is super-class of".', max_length=255, verbose_name='Name reverse'),
        ),
    ]
