# Generated by Django 2.2.11 on 2020-10-02 05:02

import apis_core.apis_relations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis_metainfo', '0001_initial'),
        ('apis_relations', '0001_initial'),
        ('apis_vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triple',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triple_prop', to='apis_vocabularies.RelationBaseClass'),
        ),
        migrations.AddField(
            model_name='triple',
            name='subj',
            field=apis_core.apis_relations.models.InheritanceForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triple_subj', to='apis_metainfo.TempEntityClass'),
        ),
    ]
