# Generated by Django 4.1.12 on 2023-12-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_relations", "0005_historicaltriple_historicaltemptriple"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltemptriple",
            name="version_tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaltriple",
            name="version_tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
