[geonames_org]
regex = '^https?://(?:[^.]*[.])?geonames[.]org/([0-9]+)'
replace = 'https://sws.geonames.org/{}/'

[d-nb_info]
regex = '^https?://(?:[^.]*[.])?d-nb.info/gnd/([0-9A-Za-u\-]+)'
replace = 'https://d-nb.info/gnd/{}'
