# Generated by Django 3.1.14 on 2022-01-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='f10_person',
            name='pers_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
