# Generated by Django 4.1.13 on 2023-12-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_entities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempentityclass",
            name="text",
        ),
    ]
