# Generated by Django 5.1.7 on 2025-05-21 08:06

import apis_core.generic.abc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0017_rename_rootobject_table'),
        ('apis_entities', '0004_delete_tempentityclass'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='AbstractEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, apis_core.generic.abc.GenericModel),

        ),
        migrations.AlterModelTable(
            name='abstractentity',
            table='entities_entity',
        ),
    ]
    database_operations = [
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations,
            state_operations
        )
    ]
