# Generated by Django 5.1.7 on 2025-05-21 08:06

from django.db import migrations, models

import apis_core.generic.abc


class Migration(migrations.Migration):
    dependencies = [
        ("apis_metainfo", "0017_remove_rootobject_from_state"),
        ("apis_entities", "0004_delete_tempentityclass"),
    ]

    state_operations = [
        migrations.CreateModel(
            name="RootObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            bases=(models.Model, apis_core.generic.abc.GenericModel),
        ),
        migrations.AlterModelTable(
            name="RootObject",
            table="apis_metainfo_rootobject",
        ),
    ]
    database_operations = []
    operations = [
        migrations.SeparateDatabaseAndState(database_operations, state_operations)
    ]
