# Generated by Django 5.2.6 on 2025-10-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("relations", "0003_relation_relations_r_subj_content_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(name="Foo", fields=[]),
        migrations.CreateModel(
            name="Bar",
            fields=[],
        ),
        migrations.CreateModel(
            name="Baz",
            fields=[],
        ),
        migrations.CreateModel(
            name="FooBarRelation",
            fields=[],
            options={
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
    ]
