[[filters]]
"rdf:type" = "gndo:DifferentiatedPerson"

[attributes]
forename = ["gndo:forename", "gndo:preferredNameEntityForThePerson/gndo:forename"]
alternative_names = "gndo:variantNameForThePerson"
surname = ["gndo:surname", "gndo:preferredNameEntityForThePerson/gndo:surname"]
start_date_written = "gndo:dateOfBirth"
end_date_written = "gndo:dateOfDeath"
same_as = "owl:sameAs"
profession = "gndo:professionOrOccupation"

relations = ["gndo:placeOfDeath", "gndo:placeOfBirth"]
