[[filters]]
"rdf:type" = "gndo:DifferentiatedPerson"

[attributes]
forename = ["gndo:forename", "gndo:preferredNameEntityForThePerson/gndo:forename"]
surname = ["gndo:surname", "gndo:preferredNameEntityForThePerson/gndo:surname"]
alternative_names = "gndo:variantNameForThePerson"
date_of_birth = "gndo:dateOfBirth"
date_of_death = "gndo:dateOfDeath"
same_as = "owl:sameAs"
profession = "gndo:professionOrOccupation"
