[[filters]]
"wdt:P31" = "wd:Q5"

[attributes]
forename = "wdt:P735/rdfs:label"
surname = "wdt:P734/rdfs:label"
date_of_birth = "wdt:P569"
date_of_death = "wdt:P570"
same_as = ["owl:sameAs", "wdtn:P227", "wdtn:P1566", "wdtn:P214", "wdtn:P244"]
