[[filters]]
"rdf:type" = "gn:Feature"


[attributes]
label = ["gn:name", "gn:officialName", "gn:alternateName"]
latitude = "wgs84_pos:lat"
longitude = "wgs84_pos:long"
same_as = ["rdfs:seeAlso", "gn:wikipediaArticle"]
