# Generated by Django 4.1.10 on 2023-07-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0004_auto_20230310_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootobject',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Label'),
        ),
    ]
