# Generated by Django 4.1.13 on 2026-02-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0005_alter_rootobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootobject',
            name='name',
            field=models.TextField(verbose_name='Label'),
        ),
    ]
