# Generated by Django 4.1.13 on 2023-12-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_entities", "0002_remove_tempentityclass_text"),
        ("apis_metainfo", "0005_delete_uricandidate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Text",
        ),
    ]
