# Generated by Django 4.1.13 on 2026-02-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0006_alter_rootobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootobject',
            name='name',
            field=models.CharField(max_length=5000, verbose_name='Label'),
        ),
    ]
