# Generated by Django 5.1.1 on 2024-09-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample_project", "0003_alter_versiongroup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="end_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="end_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="End"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="end_end_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="end_start_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="start_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="start_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Start"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="start_end_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="start_start_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="end_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="end_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="End"
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="end_end_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="end_start_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="start_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="start_date_written",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Start"
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="start_end_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="start_start_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
