# Generated by Django 5.1.1 on 2024-10-11 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample_project", "0004_person_end_date_person_end_date_written_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="person",
            name="end_date_written",
        ),
        migrations.RemoveField(
            model_name="person",
            name="end_end_date",
        ),
        migrations.RemoveField(
            model_name="person",
            name="end_start_date",
        ),
        migrations.RemoveField(
            model_name="person",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="person",
            name="start_date_written",
        ),
        migrations.RemoveField(
            model_name="person",
            name="start_end_date",
        ),
        migrations.RemoveField(
            model_name="person",
            name="start_start_date",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="end_date_written",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="end_end_date",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="end_start_date",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="start_date_written",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="start_end_date",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="start_start_date",
        ),
    ]
