# Generated by Django 5.2.4 on 2025-08-04 09:45

import django_json_editor_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample_project", "0009_versionprofession"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="alternative_labels",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="alternative_labels",
            field=django_json_editor_field.fields.JSONEditorField(
                blank=True, null=True
            ),
        ),
    ]
