# Generated by Django 5.2.6 on 2025-09-30 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample_project", "0001_squashed_0011_alter_place_feature_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iscousinof",
            options={"verbose_name": "is cousin of"},
        ),
        migrations.AlterModelOptions(
            name="ispartof",
            options={"verbose_name": "is part of"},
        ),
        migrations.AlterModelOptions(
            name="issiblingof",
            options={"verbose_name": "is sibling of"},
        ),
        migrations.AlterModelOptions(
            name="livesin",
            options={"verbose_name": "lives in"},
        ),
    ]
