# Generated by Django 4.1.12 on 2023-12-21 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_vocabularies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="texttype",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="texttype",
            name="vocabsbaseclass_ptr",
        ),
        migrations.DeleteModel(
            name="LabelType",
        ),
        migrations.DeleteModel(
            name="TextType",
        ),
    ]
