# Generated by Django 5.2.5 on 2026-06-18 08:54

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="SearchEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                ("title", models.CharField(max_length=1024)),
                ("title_slug", models.CharField(max_length=1024)),
                ("content", models.JSONField()),
                ("content_text", models.TextField(null=True)),
                ("content_text_slug", models.TextField(null=True)),
                (
                    "title_search_vector",
                    django.contrib.postgres.search.SearchVectorField(),
                ),
                (
                    "content_search_vector",
                    django.contrib.postgres.search.SearchVectorField(),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="search_sear_content_8fe2f4_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["content_text"],
                        name="search_sear_content_text_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["content_text_slug"],
                        name="search_sear_cntnt_txt_slug_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["title"],
                        name="search_sear_title_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["title_slug"],
                        name="search_sear_title_slug_gin",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["title_search_vector"],
                        name="search_sear_title_s_79aea5_gin",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["content_search_vector"],
                        name="search_sear_content_dabe76_gin",
                    ),
                ],
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
