# Generated by Django 4.1.13 on 2023-12-18 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apis_metainfo", "0006_delete_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obj",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relations_as_obj",
                        to="apis_metainfo.rootobject",
                    ),
                ),
                (
                    "subj",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relations_as_subj",
                        to="apis_metainfo.rootobject",
                    ),
                ),
            ],
        ),
    ]
