# Generated by Django 5.1.1 on 2024-10-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="relation",
            name="obj_content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relation_obj_set",
                to="contenttypes.contenttype",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relation",
            name="obj_object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relation",
            name="subj_content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relation_subj_set",
                to="contenttypes.contenttype",
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relation",
            name="subj_object_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
