# Generated by Django 5.1.1 on 2024-10-15 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0002_relation_obj_content_type_relation_obj_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="obj_content_type",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relation_obj_set",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="obj_object_id",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="relation",
            name="subj_content_type",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relation_subj_set",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="relation",
            name="subj_object_id",
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
