#SPDX-FileCopyrightText: 2023 Birger Schacht
#SPDX-License-Identifier: MIT
name: Run black Linter

on: [push, pull_request]

jobs:
  black:
    uses: acdh-oeaw/prosnet-workflows/.github/workflows/poetry-black.yml@dev
    with:
      src: "."
