#SPDX-FileCopyrightText: 2024 Birger Schacht
#SPDX-License-Identifier: MIT

name: Check if there are outdated translation files
on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install gettext
        run: sudo apt-get update && sudo apt-get -f install gettext
      - name: Make messages
        run: uv run ./manage.py makemessages -l de --add-location file
      - name: Check changes using git-diff
        run: git diff --exit-code
