#SPDX-FileCopyrightText: 2024 Birger Schacht
#SPDX-License-Identifier: MIT

name: Run javascript linter
on:
  pull_request:

jobs:
  jsbeautify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # for poetry caching, we have to install poetry before setting up python
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          cache: 'poetry'
          cache-dependency-path: "pyproject.toml"
          python-version: "3.11"
      - name: Install dev dependencies
        run: |
          poetry install --no-root --no-directory --only dev
      - name: Run js-beautify
        run: |
          if find . -name "*.js" -exec poetry run js-beautify -rn {} \; | grep -v unchanged; then
            exit 1;
          else
            exit 0;
          fi
