#SPDX-FileCopyrightText: 2024 Birger Schacht
#SPDX-License-Identifier: MIT

name: Run javascript linter
on:
  pull_request:

jobs:
  jsbeautify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dev dependencies
        run: uv sync --only-dev
      - name: Run js-beautify
        run: |
          if find apis_core -name "*.js" -exec uv run js-beautify -rn {} \; | grep -v unchanged; then
            exit 1;
          else
            exit 0;
          fi
