# SPDX-FileCopyrightText: 2023 Birger Schacht <birger.schacht@oeaw.ac.at>
# SPDX-License-Identifier: MIT
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: python
          package-name: apis-core-rdf
          bump-minor-pre-major: true
