#SPDX-FileCopyrightText: 2023 Birger Schacht
#SPDX-License-Identifier: MIT
name: Run ruff formatter

on: [push, pull_request]

jobs:
  ruff:
    uses: acdh-oeaw/prosnet-workflows/.github/workflows/poetry-ruff.yml@v0.4.2
    with:
      src: "."
      options: "format --check"
