name: Stale

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: write
    steps:
      - name: Manage Stale Issues and Pull Requests
        uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
        with:
          days-before-stale: 120
          days-before-close: 60
          remove-stale-when-updated: true
          stale-pr-label: stale
          stale-pr-message: >
            Marking this pull request as stale due to inactivity. This helps us
            focus on the active pull requests. If this pull request receives no
            comments in the next 60 days it will automatically be closed.

            If this pull request was automatically closed and you feel this pull
            request should be reopened, we encourage creating a new pull request
            linking back to this one for added context.

            Thank you!
