######################################################
# Create an E21_Person from a d-nb.info RDF endpoint #
######################################################
superclass = "apis_core.apis_entities.abc.E21_Person"
regex = "https://d-nb.info.*|/.*ramus.rdf"
[[attributes]]
# forename
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?forename
WHERE {
  ?subject gndo:forename ?default_forename .
   OPTIONAL {
    ?subject2 gndo:preferredNameEntityForThePerson ?med .
    ?med gndo:forename ?preferred_forename .
  }
  BIND(COALESCE(?preferred_forename, ?default_forename) AS ?forename)
}
"""
[[attributes]]
# surname
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?surname
WHERE {
  ?subject gndo:surname ?default_surname .
  OPTIONAL {
    ?subject2 gndo:preferredNameEntityForThePerson ?med .
    ?med gndo:surname ?preferred_surname .
  }
  BIND(COALESCE(?preferred_surname, ?default_surname) AS ?surname)
}
"""
[[attributes]]
# date_of_birth
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?date_of_birth
WHERE {
  ?subject gndo:dateOfBirth ?start_date_written
  BIND(?start_date_written AS ?date_of_birth)
}
"""
[[attributes]]
# date_of_death
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?date_of_death
WHERE {
  ?subject gndo:dateOfDeath ?end_date_written
  BIND(?end_date_written AS ?date_of_death)
}
"""
