####################################################
# Create an E53_Place from a geonames RDF endpoint #
####################################################
superclass = "apis_core.apis_entities.abc.E53_Place"
# the second regex is for the test data
regex = "https://sws.geonames.org.*|/.*achensee.rdf"
[[attributes]]
# name
#FILTER (LANGMATCHES(LANG(?prefName), "de") || LANGMATCHES(LANG(?prefName), "en") || LANG(?prefName) = "")
sparql = """
PREFIX gn: <http://www.geonames.org/ontology#>
SELECT ?label
WHERE
{
  OPTIONAL {
    ?subject gn:name ?gnname .
  }
  OPTIONAL {
   ?subject gn:officialName ?officialName
  }
  OPTIONAL {
    ?subject gn:alternateName ?alternateName
  }
  BIND(COALESCE(?gnname, ?officialName, ?alternateName) AS ?label)
}
"""
[[attributes]]
# kind
sparql = """
PREFIX gn: <http://www.geonames.org/ontology#>
SELECT ?kind
WHERE {
  ?subject gn:featureCode ?kind
}
"""
[[attributes]]
# lat
sparql = """
PREFIX wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT ?latitude
WHERE {
  ?subject wgs84_pos:lat ?latitude.
  ?subject wgs84_pos:long ?longitude
}
"""
[[attributes]]
# long
sparql = """
PREFIX wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT ?longitude
WHERE {
  ?subject wgs84_pos:lat ?latitude.
  ?subject wgs84_pos:long ?longitude
}
"""
[[attributes]]
# parent
sparql = """
PREFIX gn: <http://www.geonames.org/ontology#>
SELECT ?parent
WHERE {
  ?subject gn:parentCountry ?parent
}
"""

