#########################################
# Create an entity `apis_ontology.Person`
# from a d-nb.info RDF endpoint
#########################################
model = "apis_ontology.Person"
filter_sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
ASK {
  ?subject gndo:preferredNameForThePerson ?object .
}
"""
[[attributes]]
# name
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?name
WHERE {
  ?subject gndo:preferredNameForThePerson ?name .
  OPTIONAL {
    ?subject gndo:preferredNameEntityForThePerson ?med .
    ?med gndo:forename ?first_name.
    ?med gndo:surname ?name2 .
    BIND(?name2 as ?name)
  }
  BIND(CONCAT(?name, ",", ?first_name) AS ?name)
}
"""
[[attributes]]
# profession
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?profession
WHERE {
  ?subject gndo:professionOrOccupation ?profession
}
"""
[[attributes]]
# date_of_birth
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?date_of_birth
WHERE {
  ?subject gndo:dateOfBirth ?start_date_written
  BIND(?start_date_written AS ?date_of_birth)
}
"""
[[attributes]]
# date_of_death
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?date_of_death
WHERE {
  ?subject gndo:dateOfDeath ?end_date_written
  BIND(?end_date_written AS ?date_of_death)
}
"""
[[attributes]]
# place_of_birth
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?place_of_birth
WHERE {
  ?subject gndo:placeOfBirth ?place_of_birth
}
"""

