#########################################
# Create an entity `apis_ontology.Place`
# from a geonames RDF endpoint
##########################################
model = "apis_ontology.Place"
filter_sparql = """
PREFIX gn: <http://www.geonames.org/ontology#>
ASK {
  ?subject gn:featureClass <https://www.geonames.org/ontology#P> .
  ?subject gn:featureCode <https://www.geonames.org/ontology#P.PPL> .
}
"""
[[attributes]]
# name
sparql = """
PREFIX gn: <http://www.geonames.org/ontology#>
SELECT ?name
WHERE
{
  ?subject gn:name|gn:officialName|gn:alternateName ?prefName
  FILTER (LANGMATCHES(LANG(?prefName), "de") || LANGMATCHES(LANG(?prefName), "en") || LANG(?prefName) = "")
  BIND(?prefName AS ?name)
}
ORDER BY ?lang
"""
[[attributes]]
# alternative_label
sparql = """
PREFIX gn: <http://www.geonames.org/ontology#>
SELECT ?altName (LANG(?altName) AS ?lang)
WHERE {
  ?subject gn:alternateName ?altName
  FILTER (LANGMATCHES(LANG(?altName), "de") || LANGMATCHES(LANG(?altName), "en") || LANG(?prefName) = "")
}
"""
[[attributes]]
# kind
sparql = """
PREFIX gn: <http://www.geonames.org/ontology#>
SELECT ?kind
WHERE {
  ?subject gn:featureCode ?kind
}
"""
[[attributes]]
# lat
sparql = """
PREFIX wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT ?lat
WHERE {
  ?subject wgs84_pos:lat ?lat.
  ?subject wgs84_pos:long ?long
}
"""
[[attributes]]
# long
sparql = """
PREFIX wgs84_pos: <http://www.w3.org/2003/01/geo/wgs84_pos#>
SELECT ?long
WHERE {
  ?subject wgs84_pos:lat ?lat.
  ?subject wgs84_pos:long ?long
}
"""
[[attributes]]
# parent
sparql = """
PREFIX gn: <http://www.geonames.org/ontology#>
SELECT ?parent
WHERE {
  ?subject gn:parentCountry ?parent
}
"""

