#########################################
# Create an entity `apis_ontology.Place`
# from a d-nb.info RDF endpoint
#########################################
model = "apis_ontology.Place"
filter_sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
ASK {
  ?subject gndo:preferredNameForThePlaceOrGeographicName ?object .
}
"""
[[attributes]]
# name
sparql = """
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
SELECT ?name
WHERE {
  ?subject gndo:preferredNameForThePlaceOrGeographicName ?prefName
  BIND(?prefName AS ?name)
}
"""
[[attributes]]
# lon
sparql = '''
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
SELECT ?lon
WHERE {
  ?subject geo:hasGeometry ?geo1 .
  ?geo1 geo:asWKT ?point .
  BIND(REPLACE(str(?point), "Point \\( \\+(\\d+.\\d+).*", "$1") as ?lon)
  }
'''
[[attributes]]
# lat
sparql = '''
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
SELECT ?lat
WHERE {
  ?subject geo:hasGeometry ?geo1 .
  ?geo1 geo:asWKT ?point .
  BIND(REPLACE(str(?point), "Point \\( \\+(\\d+.\\d+) \\+(\\d+.\\d+) .$", "$2") as ?lat)
  }
'''
